<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRenGGVN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRenGGVN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRenGGVN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRenGGVN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRenGGVN\App_KernelDevDebugContainer([
    'container.build_hash' => 'RenGGVN',
    'container.build_id' => 'eb4805d1',
    'container.build_time' => 1736950746,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRenGGVN');
