<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYel6xEw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYel6xEw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYel6xEw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYel6xEw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYel6xEw\App_KernelDevDebugContainer([
    'container.build_hash' => 'Yel6xEw',
    'container.build_id' => 'cb70d8ff',
    'container.build_time' => 1736941070,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYel6xEw');
