<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZCTRsQJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZCTRsQJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZCTRsQJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZCTRsQJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZCTRsQJ\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZCTRsQJ',
    'container.build_id' => 'da3ea178',
    'container.build_time' => 1736941303,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZCTRsQJ');
